name: CI/CD pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  prepare-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    runs-on: ubuntu-latest
    needs: prepare-environment # Запускаем только если джоба prepare-environment прошла успешно
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d
